name: mid_term
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  cached_network_image: ^3.3.0
  cloud_firestore: ^4.9.2
  cupertino_icons: ^1.0.2
  date_format: ^2.0.7
  firebase_auth: ^4.10.0
  firebase_core: ^2.16.0
  firebase_storage: ^11.2.7
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.0
  image_picker: ^1.0.4
  photo_manager: ^3.5.2
  uuid: ^4.0.0
  video_player: ^2.8.1
  flutter_staggered_grid_view: ^0.7.0
  win32: ^5.1.3

  camera: ^0.10.5+9
  gap: ^3.0.1
  external_path: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
   - assets/images/image.jpg
   - images/


